spring.application.name=auth-service

jwt.secret=super-secret-key-super-secret-key
jwt.access_token.expiration_time=600000
jwt.refresh_token.expiration_time=10080000

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90

management.endpoints.web.exposure.include=health,info,metrics

resilience4j.retry.metrics.enabled=true
resilience4j.retry.instances.data-service.maxAttempts=3
resilience4j.retry.instances.data-service.waitDuration=1s
resilience4j.retry.instances.data-service.retryExceptions[0]=org.springframework.web.client.HttpServerErrorException
resilience4j.retry.instances.data-service.retryExceptions[1]=java.io.IOException
resilience4j.retry.instances.data-service.ignoreExceptions[0]=org.springframework.web.client.HttpClientErrorException

